<?php
include 'define.php';
?><!doctypehtml><html lang=ja><meta content="text/html; charset=utf-8"http-equiv=Content-Type><meta content="width=device-width,initial-scale=1"name=viewport><title>リンクについて｜<?=SITE_NAME?></title><meta content="リンクについて｜<?=SITE_DISC?>"name=description><meta content=max-image-preview:large name=robots><link href=https://oil-mafia.com/link.php rel=canonical><meta content=""property=og:url><meta content=article property=og:type><meta content="リンクについて｜<?=SITE_NAME?>"property=og:title><meta content="リンクについて｜<?=SITE_DISC?>"property=og:description><meta content=オイルマフィア property=og:site_name><meta content=""property=og:image><meta content=summary_large_image name=twitter:card><meta content=""name=twitter:site><meta content="リンクについて｜<?=SITE_NAME?>"name=twitter:title><meta content="リンクについて｜<?=SITE_DISC?>"name=twitter:description><meta content=""name=twitter:image><?php
$loc_href = '.';
$inc_path = $_SERVER["DOCUMENT_ROOT"].'/assets';
$com_href = '/assets';

include $inc_path .'/inc/head.php';
?><div class=container id=vue-app><?php include $inc_path .'/inc/side_left.php';?><div class=content><?php include $inc_path .'/inc/header.php';?><div class=sub_box><h1 class=big_h2>LINK</h1> <h2 class=sub_page>リンクの利用について</h2><p class=bottom_spa>当サイトへのリンクは、以下のURL、バナー画像、HTMLソースをご利用ください。 リンクは原則自由ですが、以下の注意事項を遵守してください。<div class="link_box box_sub_page"><ul><li>1) 本サイトのコンテンツやURLは、予告なく削除または変更する場合があります。リンクをされた方に対し、削除または変更のご連絡はいたしませんのでご注意ください。<li>2) 本サイトの趣旨に合わないホームページ、またリンクの目的が不適当(営利目的や勧誘目的等)なリンクはご遠慮願います。<li>3) リンク先のホームページに対して、第三者から、苦情、賠償、その他いかなる請求等があったとしても、弊社は何ら責任を負わないものとします。<li>4) 弊社がリンク削除の申し入れをした場合はこれに従ってください。</ul></div><h2 class=sub_page>リンク・バナー</h2><div class=link_box><p>スマホで閲覧の方は右にスクロールが可能です<table class=company-table><tr><td width=25%><i class="fa-link fa-solid"></i>URL<td width=75%><a href=https://oil-mafia.com/ >https://oil-mafia.com/</a><tr><td><i class="fa-link fa-solid"></i>バナー画像01<br>（468x60）<td><img alt=オイルマフィアバナー height=60 src=https://oil-mafia.com/images/om468_60.jpg width=468><br><span class=small_txt2>https://oil-mafia.com/images/om468_60.jpg</span><br><span class=small_txt2>▼以下のタグをコピー＆ペーストにてご利用ください。</span><br><textarea class=link_txt name=linktag onclick=this.focus(),this.select() rows=3>&lt;a href="https://oil-mafia.com/">&lt;img width="460" height="60" border="0" src="https://oil-mafia.com/images/om468_60.jpg" alt="メンズエステ・マッサージ探すならオイルマフィア">&lt;/a></textarea><tr><td><i class="fa-link fa-solid"></i>バナー画像02<br>（200x40）<td><img alt=オイルマフィアバナー height=40 src=https://oil-mafia.com/images/om200_40.jpg width=200><br><span class=small_txt2>https://oil-mafia.com/images/om200_40.jpg</span><br><span class=small_txt2>▼以下のタグをコピー＆ペーストにてご利用ください</span><br><textarea class=link_txt name=linktag onclick=this.focus(),this.select() rows=3>&lt;a href="https://oil-mafia.com/">&lt;img width="200" height="40" border="0" src="https://oil-mafia.com/images/om200_40.jpg" alt="メンズエステ・マッサージ探すならオイルマフィア">&lt;/a></textarea><tr><td><i class="fa-link fa-solid"></i>バナー画像03<br>（88x31）<td><img alt=オイルマフィアバナー height=31 src=https://oil-mafia.com/images/om88_31.jpg width=88><br><span class=small_txt2>https://oil-mafia.com/images/om88_31.jpg</span><br><span class=small_txt2>▼以下のタグをコピー＆ペーストにてご利用ください</span><br><textarea class=link_txt name=linktag onclick=this.focus(),this.select() rows=3>&lt;a href="https://oil-mafia.com/">&lt;img width="88" height="31" border="0" src="https://oil-mafia.com/images/om88_31.jpg" alt="メンズエステ・マッサージ探すならオイルマフィア">&lt;/a></textarea><tr><td><i class="fa-link fa-solid"></i>サイトタイトル<td>メンズエステ・マッサージ・出張マッサージを探すならオイルマフィア<tr><td><i class="fa-link fa-solid"></i>サイト説明文<td>メンズエステ・マッサージ・出張マッサージが探せる総合情報サイト</table></div></div><?php include $inc_path .'/inc/footer_menu.php';?></div></div><?php include $inc_path .'/inc/footer.php';?>
