<?php
include 'define.php';
?><!doctypehtml><html lang=ja><meta content="text/html; charset=utf-8"http-equiv=Content-Type><meta content="width=device-width,initial-scale=1"name=viewport><title>プライバシーポリシー｜<?=SITE_NAME?></title><meta content="プライバシーポリシー｜<?=SITE_DISC?>"name=description><meta content=max-image-preview:large name=robots><link href=https://oil-mafia.com/policy.php rel=canonical><meta content=""property=og:url><meta content=article property=og:type><meta content="プライバシーポリシー｜<?=SITE_NAME?>"property=og:title><meta content="プライバシーポリシー｜<?=SITE_DISC?>"property=og:description><meta content=オイルマフィア property=og:site_name><meta content=""property=og:image><meta content=summary_large_image name=twitter:card><meta content=""name=twitter:site><meta content="プライバシーポリシー｜<?=SITE_NAME?>"name=twitter:title><meta content="プライバシーポリシー｜<?=SITE_DISC?>"name=twitter:description><meta content=""name=twitter:image><?php
$loc_href = '.';
$inc_path = $_SERVER["DOCUMENT_ROOT"].'/assets';
$com_href = '/assets';

include $inc_path .'/inc/head.php';
?><div class=container id=vue-app><?php include $inc_path .'/inc/side_left.php';?><div class=content><?php include $inc_path .'/inc/header.php';?><div class=sub_box><h1 class=big_h2>プライバシーポリシー</h1> <h2 class=sub_page>個人情報保護方針</h2><p class=box_sub_page>弊社は、個人情報は個人の人格尊重の理念の下に慎重に取り扱われるべきものであることにかんがみ、 その適正な取扱いを図ることと致します。また、弊社はお客様の重要な情報を取り扱う企業として、 個人情報の安全管理を厳守すべき責任を認識しております。 このため、弊社は以下のとおり個人情報保護方針を定め、個人情報の適切な収集、利用、提供等に努めるとともに、 本方針を社内に周知し、かつ、外部に公表するものとします。<h3 class=sub_page><i class="fa-shield-check fa-solid"></i>個人情報の管理者</h3><p class=box_sub_page>1. 弊社は、個人情報を取り扱っている部門に個人情報の管理責任者を置き、その管理責任者に適切な個人情報の管理を行わせます。<h3 class=sub_page><i class="fa-shield-check fa-solid"></i>個人情報の収集</h3><p class=box_sub_page>2. 弊社が、個人情報を収集する場合は、利用目的をできる限り特定し、ご本人に対し、個人情報に関する弊社の窓口、個人情報の利用目的及び利用方法等を事前に通知したうえで、必要な範囲の個人情報を収集致します。ご本人に無断でまたは不公正な方法で個人情報を取得することはありません。<h3 class=sub_page><i class="fa-shield-check fa-solid"></i>個人情報の利用</h3><p class=box_sub_page>3. 弊社は、前項に基づき通知した収集目的の範囲内で個人情報の利用及び提供を行うものとし、利用目的の範囲外で個人情報の利用または提供を行う場合には、事前にご本人の承諾を得るものとします。<h3 class=sub_page><i class="fa-shield-check fa-solid"></i>個人情報の非開示</h3><p class=box_sub_page>4. 弊社は、前項に定める場合又は法令に定めのある場合を除き、ご本人の個人情報を第三者に開示することはありません。<h3 class=sub_page><i class="fa-shield-check fa-solid"></i>個人情報の安全性の確保</h3><p class=box_sub_page>5. 弊社は、個人情報への不正アクセス、個人情報の紛失、破壊、改竄及び漏洩等個人情報に関するリスクに対して、必要十分な安全対策を講ずるものとします。<h3 class=sub_page><i class="fa-shield-check fa-solid"></i>個人情報の照会及び修正</h3><p class=box_sub_page>6. ご本人が、個人情報の照会、修正等を希望される場合には、個人情報に関する弊社の窓口までご連絡をいただければ、ご本人であることを確認のうえ、合理的な範囲ですみやかに対応致します。<h3 class=sub_page><i class="fa-shield-check fa-solid"></i>個人情報の提供又は委託</h3><p class=box_sub_page>7. 弊社は、第2項の利用目的の範囲内で、弊社以外の者に個人情報を提供し、または個人情報の収集もしくは管理を委託する場合があります。この場合においては、委託または提供先が十分な個人情報保護の水準を満たすよう弊社において管理を行うものとします。<h3 class=sub_page><i class="fa-shield-check fa-solid"></i>法令の遵守及び取組みの改善</h3><p class=box_sub_page>8. 弊社は、個人情報に関して適用される法令を遵守するとともに、上記各条項における取組みを適宜見直し、継続的に改善するものとします。<h3 class=sub_page><i class="fa-shield-check fa-solid"></i>個人情報保護方針の変更</h3><p class=box_sub_page>9. 本方針の内容は、法令その他本方針に別段の定めのある事項を除いて、社会情勢や諸環境の変化に応じ、ユーザーに通知することなく変更できるものとします。また弊社が別途に定める場合を除いて、変更後の本方針は本サイトに掲載した時から効力を生じるものとします。<h3 class=sub_page><i class="fa-shield-check fa-solid"></i>附則</h3><p class=box_sub_page>1. 弊社は、利用者のサイト訪問履歴情報を採取するためのクッキーを使用しています。このクッキーは広告配信の目的のみに使用し、その他の目的には利用致しません。また、ユーザーを特定・識別する情報は一切含まれておりません。</div><?php include $inc_path .'/inc/footer_menu.php';?></div></div><?php include $inc_path .'/inc/footer.php';?>
